### ISSUE TITLE
Class "BaseCommand" does not exist in CommandDiscovery.php

### ISSUE THREAD

**Issue by manoxs** [seanhamlin/cfcli-docker#1]
Not able to run ./cfcli.phar anymore, I get the following eror
```
PHP Fatal error:  Uncaught ReflectionException: Class "BaseCommand" does not exist in phar:///home/gutierm18/Documents/Drupal/cfcli/cfcli.phar/src/CommandDiscovery.php:19
Stack trace:
#0 phar:///home/gutierm18/Documents/Drupal/cfcli/cfcli.phar/src/CommandDiscovery.php(19): ReflectionClass->__construct()
#1 phar:///home/gutierm18/Documents/Drupal/cfcli/cfcli.phar/cfcli(55): Cloudflare\CommandDiscovery::findCommands()
#2 /home/gutierm18/Documents/Drupal/cfcli/cfcli.phar(10): require('...')
#3 {main}
  thrown in phar:///home/gutierm18/Documents/Drupal/cfcli/cfcli.phar/src/CommandDiscovery.php on line 19

Fatal error: Uncaught ReflectionException: Class "BaseCommand" does not exist in phar:///home/gutierm18/Documents/Drupal/cfcli/cfcli.phar/src/CommandDiscovery.php:19
Stack trace:
#0 phar:///home/gutierm18/Documents/Drupal/cfcli/cfcli.phar/src/CommandDiscovery.php(19): ReflectionClass->__construct()
#1 phar:///home/gutierm18/Documents/Drupal/cfcli/cfcli.phar/cfcli(55): Cloudflare\CommandDiscovery::findCommands()
#2 /home/gutierm18/Documents/Drupal/cfcli/cfcli.phar(10): require('...')
#3 {main}
  thrown in phar:///home/gutierm18/Documents/Drupal/cfcli/cfcli.phar/src/CommandDiscovery.php on line 19

```

**Comment by seanhamlin** [comment]
This looks like a conflict with PHP upgrading, and the `cfcli` codebase. Likely best if you just pull an existing image from dockerhub.
